# Generated by Django 6.0.3 on 2026-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_patientnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrequest',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='donor_email',
            field=models.EmailField(max_length=30),
        ),
    ]
